merchex/merchex/urls.py
from django.contrib import admin
from django.urls import path
from listings import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("about-us/", views.about_us),
    path("contact/", views.contact, name="contact"),
    path("email-sent/", views.email_sent, name="email-sent"),
    # Band
    path("bands/", views.bands, name="bands"),
    path("bands/add/", views.band_create, name="band-create"),
    path("bands/<int:id>/", views.band_detail, name="band-detail"),
    path("bands/<int:id>/change", views.band_update, name="band-change"),
    path("bands/<int:id>/delete", views.band_delete, name="band-delete"),
    # Listing
    path("listings/", views.listings, name="listings"),
    path("listings/add/", views.listing_create, name="listing-create"),
    path("listings/<int:id>/", views.listing_detail, name="listing-detail"),
    path("listing-band/<int:id>/", views.listing_band, name="listing-band"),
    path("listings/<int:id>/change", views.listing_update, name="listing-change"),
    path("listings/<int:id>/delete", views.listing_delete, name="listing-delete"),
]

merchex/listings/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.
class Band(models.Model):
    class Genre(models.TextChoices):
        HIP_HOP = 'HH'
        SYNTH_POP = 'SP'
        ALTERNATIVE_ROCK = 'AR'
        ELECTRONIC = 'E'
        HOUSE = 'H'
        DEEP_HOUSE = 'DH'
        MINIMAL_TECH = 'MT'
        TECHNO = 'T'
        CLASSIC = 'C'
        PROGRESSIVE_ELECTRONIC = 'PE'
        INDIE_ROCK = 'IR'
    def __str__(self):
        return f'{self.name}'
    name = models.fields.CharField(max_length=50)
    genre = models.fields.CharField(choices=Genre.choices, default=Genre.HIP_HOP, max_length=2, verbose_name="Genre")
    biography = models.fields.CharField(default='', max_length=1000)
    year_formed = models.fields.IntegerField(
        default=2000,
        validators=[MinValueValidator(1900), MaxValueValidator(2021)]
    )
    active = models.fields.BooleanField(default=True)
    official_homepage = models.fields.URLField(null=True, blank=True)    
    
class Listing(models.Model):
    class Type(models.TextChoices):
        RECORDS = 'R'
        CLOTHING = 'C'
        POSTERS = 'P'
        MISCELLANEOUS = 'M'
    def __str__(self):
        return f'{self.title}'
    title = models.fields.CharField(max_length=100)
    description = models.fields.CharField(max_length=1000)
    sold = models.fields.BooleanField(default=False)
    year = models.fields.IntegerField(null=True)
    type = models.fields.CharField(choices=Type.choices, default=Type.RECORDS, max_length=2, verbose_name="Type")
    band = models.ForeignKey(Band, null=True, on_delete=models.SET_NULL)

merchex/listings/forms.py
# listings/forms.py
from django import forms
from django.core.validators import MinValueValidator, MaxValueValidator
from listings.models import Band, Listing

class ContactUsForm(forms.Form):
   name = forms.CharField(required=False)
   email = forms.EmailField()
   message = forms.CharField(max_length=1000)
   

class BandForm(forms.ModelForm):
    class Meta:
        model = Band
        exclude = ('active', 'official_homepage')  # ajoutez cette ligne
        
        
class ListingForm(forms.ModelForm):
    class Meta:
        model = Listing
        exclude = ('sold', 'band')

merchex/listings/views.py
# listings/views.py

from django.http import HttpResponse
from django.shortcuts import render, redirect
from listings.models import Band, Listing
from listings.forms import ContactUsForm, BandForm, ListingForm
from django.core.mail import send_mail

def about_us(request):
    return render(request, "listings/about-us.html")

def contact(request):
    if request.method == "POST":
        form = ContactUsForm(request.POST)
        if form.is_valid():
            send_mail(
                subject=f'Message from {form.cleaned_data["name"] or "anonyme"} via MerchEx Contact Us form',
                message=form.cleaned_data['message'],
                from_email=form.cleaned_data['email'],
                recipient_list=['admin@merchex.xyz'],
            )
            return redirect('email-sent')  # ajoutez cette instruction de retour
    else:
        form = ContactUsForm()
    return render(request, "listings/contact.html", { "form": form })

def email_sent(request):
    return render(request, "listings/email-sent.html")

def bands(request):
    bands = Band.objects.all()
    return render(request, "listings/band-list.html", { "bands": bands })

def band_detail(request, id):
    band = Band.objects.get(id=id)
    listing = Listing.objects.filter(band=id)
    return render(request, "listings/band-detail.html", { "band": band, "listing": listing })

def band_create(request):
    if request.method == 'POST':
        form = BandForm(request.POST)
        if form.is_valid():
            # créer une nouvelle « Band » et la sauvegarder dans la db
            band = form.save()
            # redirige vers la page de détail du groupe que nous venons de créer
            # nous pouvons fournir les arguments du motif url comme arguments à la fonction de redirection
            return redirect('band-detail', band.id)
    else:
        form = BandForm()
    return render(request,
            'listings/band-create.html',
            { 'form': form })
    
def band_update(request, id):
    band = Band.objects.get(id=id)
    if request.method == 'POST':
        form = BandForm(request.POST, instance=band)
        if form.is_valid():
            # mettre à jour le groupe existant dans la base de données
            form.save()
            # rediriger vers la page détaillée du groupe que nous venons de mettre à jour
            return redirect('band-detail', band.id)
    else:
        form = BandForm(instance=band)
    return render(request,
            'listings/band-update.html',
            { 'form': form })
    
def band_delete(request, id):
    band = Band.objects.get(id=id)
    if request.method == 'POST':
        band.delete()
        return redirect('bands')
    return render(request,
           'listings/band-delete.html',
           { 'band': band })
    
def listings(request):
    listings = Listing.objects.all()
    return render(request, "listings/listings.html", { "listings": listings })

def listing_band(request, id):
    band = Band.objects.get(id=id)
    return render(request, "listings/listing-band.html", { "band": band })

def listing_detail(request, id):
    listing = Listing.objects.get(id=id)
    return render(request, "listings/listing-detail.html", { "listing": listing })

def listing_create(request):
    if request.method == 'POST':
        form = ListingForm(request.POST)
        if form.is_valid():
            # créer une nouvelle « Band » et la sauvegarder dans la db
            listing = form.save()
            # redirige vers la page de détail du groupe que nous venons de crtéer
            # nous pouvons fournir les arguments du motif url comme arguments à la fonction de redirection
            return redirect('listing-detail', listing.id)
    else:
        form = ListingForm()
    return render(request,
            'listings/listing-create.html',
            { 'form': form })

def listing_update(request, id):
    listing = Listing.objects.get(id=id)
    if request.method == 'POST':
        form = ListingForm(request.POST, instance=listing)
        if form.is_valid():
            # mettre à jour le groupe existant dans la base de données
            form.save()
            # rediriger vers la page détaillée du groupe que nous venons de mettre à jour
            return redirect('listing-detail', listing.id)
    else:
        form = ListingForm(instance=listing)
    return render(request,
            'listings/listing-update.html',
            { 'form': form })
    
def listing_delete(request, id):
    listing = Listing.objects.get(id=id)
    if request.method == 'POST':
        listing.delete()
        return redirect('listings')
    return render(request,
           'listings/listing-delete.html',
           { 'listing': listing })

merchex/listings/templates/listings/about-us.html
{% extends "listings/base.html" %}
{% block content %}
    <h1>About us</h1>
    <p>This is the about us page</p>
{% endblock %}

merchex/listings/templates/listings/band-create.html
{% extends "listings/base.html" %}
{% block content %}
<h1>Create a new Band: </h1>
<form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
</form>
{% endblock %}

merchex/listings/templates/listings/band-delete.html
{% extends "listings/base.html" %}
{% block content %}
<h1>Supprimer le groupe</h1>
<p>Etes-vous sûr de vouloir supprimer le groupe : {{ band.name }} ?</p>


<form action="" method="post">
{% csrf_token %}
<input type="submit" value="Supprimer">
</form>
{% endblock %}

merchex/listings/templates/listings/band-detail.html
{% extends "listings/base.html" %}
{% block content %}
<a href="{% url 'band-change' band.id %}">Modifier le groupe</a>
<a href="{% url 'band-delete' band.id %}">Supprimer le groupe</a>
<h1>{{ band.name }} :</h1>
<ul> 
    <li>Genre : {{ band.get_genre_display }}</li>
    <li>Date de formation : {{ band.year_formed }}</li>
    <li>Actif : {{ band.active|yesno }}</li>
    {% if band.official_homepage %}
    <li><a href="{{ band.official_homepage }}" target="blank">Site officiel</a></li>
    {% endif %}
    {% if listing %}
    <li>
        <a href="{% url 'listing-band' band.id %}" target="blank">Listing de {{ band.name }}</a>
    </li>
    
    {% endif %}
</ul>
<p>{{ band.biography }}</p>
{% endblock %}

merchex/listings/templates/listings/band-list.html
{% extends "listings/base.html" %}
{% block content %}
<h1>Groupes :</h1>
<a href="{% url 'band-create' %}">Créer un nouveau groupe</a>
<ul>
    {% for band in bands %}
    <li>
        <a href="{% url 'band-detail' band.id %}">{{ band.name }}</a>
        - <a href="{% url 'band-change' band.id %}">[modifier]</a>
        - <a href="{% url 'band-delete' band.id %}">[supprimer]</a>
    </li>
    {% endfor %}
</ul>
{% endblock %}

merchex/listings/templates/listings/band-update.html
{% extends "listings/base.html" %}
{% block content %}
<h1>Update band: </h1>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
</form>
{% endblock %}

merchex/listings/templates/listings/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>Merchex</title>
        <link rel="stylesheet" href="{% static 'listings/styles.css' %}">
    </head>
    <body>
        <nav>
            <a href="{% url 'bands' %}">Groupes</a>
            <a href="{% url 'listings' %}">Listings</a>
            <a href="{% url 'contact' %}">Contact us</a>
        </nav>
        {% block content %}{% endblock %}
    </body>
</html>

merchex/listings/templates/listings/email-sent.html
{% extends "listings/base.html" %}
{% block content %}
<h1>Email Sent</h1>
{% endblock %}

merchex/listings/templates/listings/listing-band.html
{% extends "listings/base.html" %}
{% block content %}
<nav>
    <a href="{% url 'band-detail' band.id %}">{{ band.name }}</a>
</nav>
    <h1>Listings du groupe {{ band.name }} :</h1>
    <ul>
        {% for listing in band.listing_set.all %}
        <li><a href="{% url 'listing-detail' listing.id %}">{{ listing.title }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

merchex/listings/templates/listings/listing-create.html
{% extends "listings/base.html" %}
{% block content %}
<h1>Create a new Listing: </h1>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
</form>
{% endblock %}

merchex/listings/templates/listings/listing-delete.html
{% extends "listings/base.html" %}
{% block content %}
<h1>Supprimer le listing</h1>
<p>Etes-vous sûr de vouloir supprimer le listing : {{ listing.title }} ?</p>


<form action="" method="post">
{% csrf_token %}
<input type="submit" value="Supprimer">
</form>
{% endblock %}

merchex/listings/templates/listings/listing-detail.html
{% extends "listings/base.html" %}
{% block content %}
<a href="{% url 'listing-change' listing.id %}">Modifier le listing</a>
<a href="{% url 'listing-delete' listing.id %}">Supprimer le listing</a>
{% if listing.band %}
<h1>Listing pour le groupe {{ listing.band }} </h1>
{% else %}
<h1>Listing</h1>
{% endif %}
<ul>
    <li>Titre : {{ listing.title }}</li>
    {% if listing.description %}
    <li>Description : {{ listing.description }}</li>
    {% endif %}
    {% if listing.year %}
    <li>Date: {{ listing.year }}</li>
    {% endif %}
    <li>Type : {{ listing.get_type_display }}</li>
</ul>
{% endblock %}

merchex/listings/templates/listings/listing-update.html
{% extends "listings/base.html" %}
{% block content %}
<h1>Update listing: </h1>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
</form>
{% endblock %}

merchex/listings/templates/listings/listings.html
{% extends "listings/base.html" %}
{% block content %}
<a href="{% url 'listing-create' %}">Créer un nouveau listing</a>
<h1>Listings :</h1>
<ul>
    {% for listing in listings %}
        <li>
            <a href="{% url 'listing-detail' listing.id %}">{{ listing.title }}</a>
            - <a href="{% url 'listing-change' listing.id %}">[modifier]</a>
            - <a href="{% url 'listing-delete' listing.id %}">[supprimer]</a>
        </li>
    {% endfor %}
</ul>
{% endblock %}